# Generated by Django 4.2.4 on 2023-08-25 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaryapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Date',
            new_name='Data',
        ),
    ]
