# Generated by Django 4.2.4 on 2023-08-26 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaryapp', '0002_rename_date_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='text',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
