# Generated by Django 4.2.4 on 2023-08-26 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaryapp', '0004_diary_remove_data_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='diary',
            field=models.TextField(null=True),
        ),
    ]
