# Generated by Django 4.2.4 on 2023-08-26 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaryapp', '0005_alter_diary_diary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='conversation',
            field=models.TextField(null=True),
        ),
    ]
