# Generated by Django 4.2.4 on 2023-08-26 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaryapp', '0006_alter_diary_conversation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='conversation',
        ),
    ]
