# Generated by Django 4.2.4 on 2023-08-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaryapp', '0008_diary_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='img',
        ),
        migrations.AddField(
            model_name='data',
            name='url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
